name: posthog_flutter
description: Flutter implementation of Posthog client for iOS, Android and Web
version: 2.0.0
homepage: https://www.posthog.com
repository: https://github.com/posthog/posthog-flutter
issue_tracker: https://github.com/posthog/posthog-flutter/issues
documentation: https://github.com/posthog/posthog-flutter#readme

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.posthog.posthog_flutter
        pluginClass: PosthogFlutterPlugin
      ios:
        pluginClass: PosthogFlutterPlugin
      web:
        pluginClass: PosthogWeb
        fileName: src/posthog_web.dart
